//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Action_GunArm.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Action_GunArm: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Action_GunArm()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Action_GunArm"",
    ""maps"": [
        {
            ""name"": ""GunArm"",
            ""id"": ""772afb12-1418-4a85-a60d-e4217402ed97"",
            ""actions"": [
                {
                    ""name"": ""Lean_Left"",
                    ""type"": ""Value"",
                    ""id"": ""e21e2517-070b-4d0d-9eca-46943f5e3a85"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Lean_Right"",
                    ""type"": ""Value"",
                    ""id"": ""3b0beaf9-a539-4504-b34b-fed785dfd693"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Fire"",
                    ""type"": ""Button"",
                    ""id"": ""2db21817-9b77-42fb-83be-07116355f825"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""833b7139-fdbc-4ae4-9571-cdd44b78209b"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";PC"",
                    ""action"": ""Fire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ec76e611-9579-4570-9fda-7f4ba8a1f116"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";PC"",
                    ""action"": ""Lean_Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""57d9a4dd-c307-4f4a-961e-593bcb1e6967"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";PC"",
                    ""action"": ""Lean_Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""PC"",
            ""bindingGroup"": ""PC"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // GunArm
        m_GunArm = asset.FindActionMap("GunArm", throwIfNotFound: true);
        m_GunArm_Lean_Left = m_GunArm.FindAction("Lean_Left", throwIfNotFound: true);
        m_GunArm_Lean_Right = m_GunArm.FindAction("Lean_Right", throwIfNotFound: true);
        m_GunArm_Fire = m_GunArm.FindAction("Fire", throwIfNotFound: true);
    }

    ~@Action_GunArm()
    {
        UnityEngine.Debug.Assert(!m_GunArm.enabled, "This will cause a leak and performance issues, Action_GunArm.GunArm.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GunArm
    private readonly InputActionMap m_GunArm;
    private List<IGunArmActions> m_GunArmActionsCallbackInterfaces = new List<IGunArmActions>();
    private readonly InputAction m_GunArm_Lean_Left;
    private readonly InputAction m_GunArm_Lean_Right;
    private readonly InputAction m_GunArm_Fire;
    public struct GunArmActions
    {
        private @Action_GunArm m_Wrapper;
        public GunArmActions(@Action_GunArm wrapper) { m_Wrapper = wrapper; }
        public InputAction @Lean_Left => m_Wrapper.m_GunArm_Lean_Left;
        public InputAction @Lean_Right => m_Wrapper.m_GunArm_Lean_Right;
        public InputAction @Fire => m_Wrapper.m_GunArm_Fire;
        public InputActionMap Get() { return m_Wrapper.m_GunArm; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GunArmActions set) { return set.Get(); }
        public void AddCallbacks(IGunArmActions instance)
        {
            if (instance == null || m_Wrapper.m_GunArmActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GunArmActionsCallbackInterfaces.Add(instance);
            @Lean_Left.started += instance.OnLean_Left;
            @Lean_Left.performed += instance.OnLean_Left;
            @Lean_Left.canceled += instance.OnLean_Left;
            @Lean_Right.started += instance.OnLean_Right;
            @Lean_Right.performed += instance.OnLean_Right;
            @Lean_Right.canceled += instance.OnLean_Right;
            @Fire.started += instance.OnFire;
            @Fire.performed += instance.OnFire;
            @Fire.canceled += instance.OnFire;
        }

        private void UnregisterCallbacks(IGunArmActions instance)
        {
            @Lean_Left.started -= instance.OnLean_Left;
            @Lean_Left.performed -= instance.OnLean_Left;
            @Lean_Left.canceled -= instance.OnLean_Left;
            @Lean_Right.started -= instance.OnLean_Right;
            @Lean_Right.performed -= instance.OnLean_Right;
            @Lean_Right.canceled -= instance.OnLean_Right;
            @Fire.started -= instance.OnFire;
            @Fire.performed -= instance.OnFire;
            @Fire.canceled -= instance.OnFire;
        }

        public void RemoveCallbacks(IGunArmActions instance)
        {
            if (m_Wrapper.m_GunArmActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGunArmActions instance)
        {
            foreach (var item in m_Wrapper.m_GunArmActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GunArmActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GunArmActions @GunArm => new GunArmActions(this);
    private int m_PCSchemeIndex = -1;
    public InputControlScheme PCScheme
    {
        get
        {
            if (m_PCSchemeIndex == -1) m_PCSchemeIndex = asset.FindControlSchemeIndex("PC");
            return asset.controlSchemes[m_PCSchemeIndex];
        }
    }
    public interface IGunArmActions
    {
        void OnLean_Left(InputAction.CallbackContext context);
        void OnLean_Right(InputAction.CallbackContext context);
        void OnFire(InputAction.CallbackContext context);
    }
}
